### ISSUE TITLE
Updating Code of Conduct

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/reproducible-project-template#15]
### Summary

* We've had some feedback in UA (who have forked this for uatk-admin repo) that the CoC was a surprise to some and that the recourse did not some fit for our policies at Turing
* The CoC in this repo seems to be from a university source and not the one we use in TTW/TPS CoC either, so seems like its due for an update esp as more Turing folks fork this repo for their projects

### What needs to be done?

- [x] Feedback on how old CoC was chosen for this repo
- [x] Update CoC

### Who can help?

* Perhaps from @malvikasharan or @EKaroune who I believe were most active in the creation of this resource

---

### Updates

*

**Comment by malvikasharan** [comment]
The purpose for this repo is to demo how project should look like -- an empty CoC is not ideal, especially to manage interaction on the repo.
Each project should take responsibility for how they use CoC, this repo is a recommendation and not so much enforcement. If they fork and don't update this for their repo, it clearly reflects neglect from their sides and maybe even suggest that CoC is used as a box checking thing rather than a commitment.

Maybe a suggestion on the top of the file "UPDATE THIS FOR YOUR OWN REPO" and "Here are the steps for adopting this CoC for your project".

**Comment by dingaaling** [comment]
Fixed by #17
